apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhods-od-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhods-od-app
    app.kubernetes.io/part-of: rhods-od-app
  name: rhods-od-app
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: rhods-od-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: rhods-od-app
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/cchase-tenant/rhods-od-app/rhods-od-app@sha256:108c9fce1500aeb669857edf33c98d893c555696b6df6e470784ba91f1fbc1e6
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 500Mi
status: {}
