apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhods-od-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhods-od-app
    app.kubernetes.io/part-of: rhods-od-app
  name: rhods-od-app
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: rhods-od-app
status:
  loadBalancer: {}
