apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhods-od-app
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/cchase-tenant/rhods-od-app/rhods-od-app@sha256:108c9fce1500aeb669857edf33c98d893c555696b6df6e470784ba91f1fbc1e6
        name: my-python
        resources: {}
status: {}
